#!/usr/bin/env bash
#
# install-mirror-autopull.sh — run ONCE on the MIRROR server (.76) as root.
#
# Makes .76 fully hands-off for policy sync:
#   1. opts into the dev-server exported-policy seed (DLP_SEED_EXPORTED_POLICIES=1),
#   2. installs an hourly cron that pulls the latest manager/dashboard images and
#      recreates ONLY those services when the image actually changed,
#   3. applies the current images immediately.
#
# The data tier (postgres/mongo/redis/opensearch) is never touched.
#
# One-liner:
#   curl -fsSL https://raw.githubusercontent.com/effaaykhan/cybersentineldlp-prod/main/scripts/install-mirror-autopull.sh | sudo bash
#
# Env overrides: INSTALL_DIR (default /opt/cybersentineldlp),
#                COMPOSE_FILE (default docker-compose.prod.yml),
#                SERVICES (default "manager dashboard"),
#                CRON_MINUTE (default 37).
#
set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/cybersentineldlp}"
COMPOSE="${COMPOSE_FILE:-docker-compose.prod.yml}"
SERVICES="${SERVICES:-manager dashboard}"
CRON_MINUTE="${CRON_MINUTE:-37}"
ENV_FILE="$INSTALL_DIR/.env"
WRAPPER="$INSTALL_DIR/auto-pull.sh"
MIRROR_OVERRIDE="docker-compose.mirror.yml"     # relative to INSTALL_DIR
LOG="/var/log/cybersentineldlp-autopull.log"

[ "$(id -u)" = "0" ] || { echo "run as root (sudo)"; exit 1; }
command -v docker >/dev/null || { echo "docker not found"; exit 1; }
[ -f "$INSTALL_DIR/$COMPOSE" ] || { echo "compose not found at $INSTALL_DIR/$COMPOSE — set INSTALL_DIR"; exit 1; }

# 1) Opt into the exported-policy seed (idempotent).
if [ -f "$ENV_FILE" ]; then
    if ! grep -q '^DLP_SEED_EXPORTED_POLICIES=' "$ENV_FILE"; then
        printf '\n# Apply policies synced from the dev server\nDLP_SEED_EXPORTED_POLICIES=1\n' >> "$ENV_FILE"
        echo "[+] added DLP_SEED_EXPORTED_POLICIES=1 to .env"
    else
        echo "[+] DLP_SEED_EXPORTED_POLICIES already set"
    fi
else
    echo "[!] $ENV_FILE not found — add DLP_SEED_EXPORTED_POLICIES=1 yourself"
fi

# 2) Write a NON-DESTRUCTIVE compose override that forces the exported-policy
#    seed on this server. This makes the flag reach the manager container even if
#    this server's docker-compose.prod.yml predates the env passthrough (the prod
#    compose forwards ${DLP_SEED_EXPORTED_POLICIES}, but an older copy here may
#    not). Applied as a second -f, so the base compose is never edited.
cat > "$INSTALL_DIR/$MIRROR_OVERRIDE" <<'OVR'
# Mirror-only override (generated by install-mirror-autopull.sh). Forces the
# .204 policy export to seed here. Used as: -f docker-compose.prod.yml -f this.
services:
  manager:
    environment:
      - DLP_SEED_EXPORTED_POLICIES=1
OVR
echo "[+] wrote $INSTALL_DIR/$MIRROR_OVERRIDE"

# 3) Write the auto-pull wrapper (paths baked in; run-time bits escaped). It uses
#    BOTH compose files so every recreate re-applies the seed flag.
cat > "$WRAPPER" <<WRAP
#!/usr/bin/env bash
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
cd "$INSTALL_DIR" || exit 1
echo "===== autopull \$(date -Is 2>/dev/null || date) ====="
# Retry the pull — large GHCR layers can drop mid-download ("unexpected EOF").
# Completed layers are cached so each retry resumes. If it never completes we
# skip up -d and leave the running containers untouched, so we never recreate a
# service onto a half-pulled/stale image; the next run retries.
tries=0
until docker compose -f "$COMPOSE" -f "$MIRROR_OVERRIDE" pull $SERVICES; do
  tries=\$((tries+1))
  if [ \$tries -ge 5 ]; then
    echo "pull still failing after \$tries attempts — leaving containers as-is; will retry next run"
    echo "===== done (pull failed) \$(date -Is 2>/dev/null || date) ====="
    exit 1
  fi
  echo "pull interrupted — retry \$tries/5 in 30s (cached layers resume)"
  sleep 30
done
# up -d recreates ONLY services whose image/config changed; a no-op otherwise.
docker compose -f "$COMPOSE" -f "$MIRROR_OVERRIDE" up -d $SERVICES
echo "===== done \$(date -Is 2>/dev/null || date) ====="
WRAP
chmod +x "$WRAPPER"
echo "[+] wrote $WRAPPER"

# 4) Install hourly cron + logrotate (preserving other crontab entries).
touch "$LOG"
tmp="$(mktemp)"
crontab -l 2>/dev/null | grep -vE "auto-pull\.sh|CyberSentinel DLP — mirror auto-pull" > "$tmp" || true
grep -q '^MAILTO=' "$tmp" || printf 'MAILTO=""\n' >> "$tmp"
printf '%s\n%s %s\n' \
  "# CyberSentinel DLP — mirror auto-pull (dev policies -> here)" \
  "${CRON_MINUTE} * * * *" "$WRAPPER >> $LOG 2>&1" >> "$tmp"
crontab "$tmp"; rm -f "$tmp"
echo "[+] installed hourly cron (minute ${CRON_MINUTE})"

cat > /etc/logrotate.d/cybersentineldlp-autopull <<'ROT'
/var/log/cybersentineldlp-autopull.log {
    weekly
    rotate 4
    compress
    missingok
    notifempty
    copytruncate
}
ROT

# 5) Apply now: pull the current image + recreate manager WITH the seed flag.
#    This both updates a stale image and re-runs the seeder (which tops up the
#    exported policies via INSERT ... ON CONFLICT DO NOTHING).
echo "[+] applying current images now (updates image + seeds exported policies)…"
bash "$WRAPPER" || true

echo
echo "Done. This server now auto-pulls hourly (minute ${CRON_MINUTE}) and applies"
echo "policies synced from the dev server. Log: $LOG"
